node ('master'){
    tool name: 'nodejs', type: 'nodejs'
    stage('CHECKOUT'){
        sh 'echo "######################## CHECKOUT STAGE ###################################" '
        git credentialsId: 'deepteshgithub', url: 'https://github.com/deepteshb/tourofheroes.git'
        /*git 'https://github.com/deepteshb/tourofheroes.git' */
    }
    stage('BUILD'){
        sh 'echo "######################### BUILD STAGE ##################################" '
        sh 'npm build'
        sh 'npm install'
    }

    stage('STATIC CODE ANALYSIS'){
        sh 'echo "######################### STATIC CODE ANALYSIS ##################################" '
        sh 'npm run sonar'
            }

     stage('TEST'){
        sh 'echo "######################### TEST STAGE ##################################" '
        sh 'npm run test'
    }
}