node {
    tool name: 'nodejs', type: 'nodejs'
    stage('CHECKOUT'){
        sh 'echo "######################## CHECKOUT STAGE ###################################" '
        git credentialsId: 'github', url: 'https://github.com/deepteshb/tourofheroes.git'
    }
    stage('BUILD'){
        sh 'echo "######################### BUILD STAGE ##################################" '
        sh 'npm install'
        sh 'npm build'
        
    }

    stage('STATIC CODE ANALYSIS'){
        sh 'echo "######################### STATIC CODE ANALYSIS FROM CODE ITSELF ##################################" '
        sh 'npm run sonar'
            }
}

